[metadata]
name = "layout"
description = "Browse layout files"

[source]
command = "fd --type f '^layout\\.'"

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "tokyonight_night" }
