[metadata]
name = "tsx"
description = "Browse tsx files"

[source]
command = "fd --type f --extension tsx"

[preview]
command = "bat --style=plain --color=always {}"

[keybindings]
ctrl-e = "actions:open"

[actions.open]
command = "nvim '{}'"
mode = "execute"
