[metadata]
name = "tsx"
description = "Browse tsx files"

[source]
command = "fd --type f --extension tsx"

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "tokyonight_night" }

[keybindings]
ctrl-e = "actions:open"

[actions.open]
command = "nvim '{}'"
mode = "execute"
